### ISSUE TITLE
Document bigint_helper_methods usage

### ISSUE THREAD

**Issue by Sjors** [halseth/elftrace#15]
Since this requires a nightly rust compiler build, it would be good to document where it's used (and when it's no longer needed).

**Comment by Sjors** [comment]
You could also add a a `rust-toolchain.toml` with

```toml
[toolchain]
channel = "nightly"
```

So it just works(tm) on a system with a regular release of rust.
